# Methods for Behavioural Experiments

## ***General Methods***
  
### *Predators Used*

Two generalist predators of *Drosophila melanogaster* were used throughout experimentation, zebra jumping spiders (*Salticus scenicus*) and Chinese praying mantids (*Tenodera aridifolia sinensis*). The zebra jumping spiders were collected along warm sunlight walls around Michigan State University and McMaster University campuses, and regions of Southern Ontario. The spiders were housed individually in vials at 21 C, 60% humidity and a 12:12 light:dark cycle and fed laboratory populations of flies, unless in use within population cages or prior to any experiments requiring a specific feeding regime. The Chinese praying mantids were brought into the laboratory as egg cases, either collected from fields in Southern Michigan or purchased from Nature’s Control Oregon (http://www.naturescontrol.com/). Ecolosed mantids were housed in a 32.5cm^3 mesh cages (Bugdorm-43030) and fed and maintained similarly to the spiders.


### *Populations used*

  Two different populations of *Drosophila melanogaster* were used throughout experimentation for either studying the plastic response or evolved response to predation. To measure the plastic effects of predation, a population of recently caught wild flies with little adaptation to the laboratory environment was used (Baxter et al. 2015). Using 12 populations of experimentally evolved flies undergoing different predator selection regimes allows for a measure of the evolutionary effects on *Drosophila* due to predation (DeNieu 2014, Hangartner et al. 2017).
  
***Population of Recently Captured Flies***

This population of flies was collected in 2014 in Southern Ontario and maintained in large population cage at 25 C, 60% humidity and 12:12 light:dark cycle (lights on at 10:00 am) on a sucrose-cornmeal medium with live yeast (see General Methods: Baxter *et al.* 2015). Experimental flies were reared at similar conditions for activity experiments. For the courtship and copulation analysis, this population was housed with lights on at 8:00 am, with 12 hours of light, and reared on a molasses-cornmeal medium.
 
***Experimentally Evolved Populations with Predation Selection***

  In 2010, wild *Drosophila melanogaster* were collected at Fenn Valley vineyard in Southwest Michigan as a starting population for experimental evolution. After splitting this population into twelve 32.5 cm^3 Bugdorm mesh cages (~1500 flies per cage), each was designated a treatment. Four populations were controls with no predators present, four populations were continuously exposed to ~30 zebra jumping spiders and four populations were continuously exposed to ~30 1st instar Chinese praying mantids, with new predators cycled throughout. Each population of overlapping generations was maintained on a 12:12 light:dark cycle at 40% humidity and 24 C initially (for age-dependent mating experiments), and moved buildings/growth chambers in 2015 to McMaster University, housed at 60% relative humidity and 21 C (for activity analysis and light:dark mating assays). Each population was given 200 mL molasses-cornmeal-yeast food bottles, which was added every 5 days (removing the oldest bottle after 25 days), and moved to clean cages monthly. As these populations have overlapping generations, there is no exact measure of the generations of evolution to have occurred, but is estimated to be ~ 16 generations per year.

### *Statistical Analysis*

While there were distinct models fit for each analysis depending on the behaviours measured and the populations used, there are several important processes and packages used throughout. Analysis was done in R version 3.3.2 (R Core Team, 2016). For fitting (generalized) linear mixed models, the lmer() and glmer() functions were used (*lme4* package version 1.1.12, Bates *et al.* 2015). The *tidyverse* set of packages (version 1.1.0, Wickham 2017) was used for data cleaning and plotting, and the Anova function (*car* package, version 2.1.4, Fox and Weisberg 2011) was used for p-values and Wald Type II Chi-Square values. Each experiment required specific definition of fixed and random effects, and although some experiments that were completed on separate days included measures of humidity, temperature and barometric pressure, these were not ultimately included in the models, as the random effect of day was believed to encompass these effects. Indeed including the random effect of day along with the fixed effects of humidity, temperature and pressure resulted in something analogous to multi-collinearity and resulted in poor convergence of models. While not shown, the results for the biological effects of interest were largely similar whether random effects of day were included or alternatively the fixed effects of day to day variation in temperature, humidity and barometric pressure.

## ***Experimental Methods: Plastic Response***

### Measures of *Drosophila* Activity with Different Olfactory Stimuli

All activity data collection was done using two ***D**rosophila* ***A**ctivity* ***M**onitors* (DAM; Trikinetics), which counts the total times a fly crosses a laser that sits at the middle of a vial each minute over the experimental duration. These monitors were held within an undisturbed humidified chamber at 25 C with controlled hours of light (10AM) to dark (10PM). These monitors can hold small vials (22mm wide by 48 mm long) that have a snap cap lid (with ventilation hole). After the addition of ~4 ml of food (12 mm high), there is a 7mm gap between the food and the laser that will record activity.

Many different combinations of only olfactory cues was used for these experiments, using a combination of zebra jumping spiders, Chinese praying mantids, field crickets and con-specific ''stimuli'' flies. Mantid cues were compared with a control of no cues present, comparing the effect mantid olfactory cues have on ''focal'' fly activity compared to no predator present. Spiders olfactory cues effect on *Drosophila* activity was compared to many variable cues, including spider olfactory cues compared to no cue controls, like with mantids. To ensure any effect seen when comparing spider cues vs. no cues is not a product of any novel olfactory cues present in the vial (neophobia), the flies activity was recorded when exposed to spider or cricket olfactory cues. Lastly, a 4 way comparison between cricket cues, ''stimuli'' fly cues, and 2 cues from spider with different diets (cricket or fly diet) was also used. Here the effect on activity by con-specific olfactory cues (i.e. ''stimuli'' flies) can be observed, as well as the effect spider diet (spider fed flies or spider fed crickets) has on the fly activity, while controlling for potential neophobia (crickets). Each comparison above was completed together over 24 hours in two monitors, generally ranging between 12-16 flies assayed for each treatment.

All stimuli (cues) were acclimated for 3 days prior to experiment, with a spider, mantid or cricket housed singly within vials, and ''stimuli'' flies acclimated as a trio (all males). On the third day of acclimation, the ''cue'' individuals were removed along with any accompanying silks from spiders, leaving only the olfactory cues within the vials. One live sexed male ''focal'' fly from the wild caught population was aspirated into the vial. Recordings count activity over 24 hours and the data is outputted as a minute by minute count of activity for each vial.

To account for the effects of circadian rhythm on activity, two methods were used, either imposing a circadian periodicity (sin(pi x hour/12) + cos(pi x hour/12)) or fitting a natural smooth cubic spline with 5 knots (ns(hour, 5)) for hours. As both methods showed similar results with respect to the estimated parameters of interest (results not shown), only the periodicity method is used. 

### Observing the Influence of Predators on Mating in *Drosophila*

### Courtship Behaviours

Using immature females (under 24 hours old), male courtship displays were recorded. Immature females will reject all male copulation attempts (Manning 1967) meaning the females should behave similarly regardless of predation. This allows for recordings of only males adjustments of courtship strategies in response to predation without any confounding effects of female acceptance or rejection behaviours. Using the recently caught population of flies (\ref{FRESH}), reared on molasses food medium, virgin male flies were collected via aspiration. These males were housed individually for two days, allowing for no social or sexual interactions prior to the experiment. After clearing all flies in the morning before the planned experimental day, virgin females were collected in the afternoon and housed with 5 females in a vial with live yeast. Both males and females were housed at $25^\circ$C, 60\% humidity and 12:12 light dark cycle prior to the experiment. At the flies regular ``sunrise'' (8:00 am) a male was added (via aspiration) to a modified \SI{4}{\centi\meter} wide petri dish that has a layer of mesh separating the flies (on top) and a spider predator (if present) on the bottom. The spider petri dishes had the spiders acclimated 12 hours prior to the addition of the mating pair. The female was then added to the petri dish (via aspiration) and placed in an enclosed bin with a video camera recording from above (Fig. \,\ref{matebin}). Video recordings were completed for 64 mating pairs for each treatment using Logiteck C920 HD Pro webcams, recording four chambers for 15 minutes for each assay (Fig. \,\ref{matecham}). Recordings were scored using a custom script which allows for convenient input of courtship initiation and duration. The same model layout was used for both courtship proportion and courtship counts (below, changing the response variable),  which had the primary interest on the fixed effect of treatment (predator vs. no predator), with date used as a random effect that encompasses daily humidity and temperature.

### Copulation Behaviours

Following a similar protocol to recording courtship behaviours, copulation times were recorded for the wild caught population (\ref{FRESH}). Here 2 same aged virgin flies (2 days old) were used, either housed individually (males) or with 4 other flies (females). As the peak receptivity for flies is \textasciitilde3 days old, 2 day old males and females were used expecting moderate receptivity to copulation for the mating pair (Manning 1967). Video recordings of mating pairs was done for 30 minutes (or until the end of copulation) above four \SI{4}{\centi\meter} petri dishes within an enclosed bin with either spiders in the modified petri dish or no predators (Fig. \,\ref{matebin} and Fig. \,\ref{matecham}). These videos were manually scored for copulation latency and duration, and analyzed identically to the model above, with the exception of glmer() needed for copulation occurrence due to the binomial data. Results are also displayed similarly to courtship analysis. Eighty individual mating pairs were used for analysis of latency and duration, accounting for a little over 50\% of the individual pairs assayed for copulation occurrence (70 recordings for each treatment).

##  ***Experimental Methods: Evolutionary Response***

### Activity Measures of Evolved Populatons
When analyzing the activity of the evolved populations, activity was measured similarly to those above for plastic response to predatory cues with the excpetion that all populations and vials were experiencing no cues. After 2 generations reared in bottles without predators present (to remove any plastic or maternal effects due to predation), each population was recorded in the **DAM**. As there were many more replicates and populations of flies to measure, this was repeated in many blocks of data collection resulting in 240 individuals assayed (80 per treatment).

### Courtship and Copulation Measures in experimentally evolved lineages

Using the predatory evolved populations, the evolved mating times after several years of experimental evolution with (and without) predators was examined, looking for evolved shifts in peak receptive age as well as shifts in overall behaviours (A.P.). To remove any maternal effects and direct predator cues experienced by larva, populations were allowed to lay eggs in a bottle, which was then removed from the predation environment into a separate incubator with no predators present. 100 adults from the F1 generation were collected and placed in a fresh bottle, allowing egg laying for 24 hours. This process was continued to have fresh F2 individuals eclosing every 2 days for 14 days of collections. These F2 offspring were used in experiments, having adults with no predatory exposure.
             
The virgin males and virgin females collected were placed into 4 age categories (age bins by days old: 1) 1-3, 2) 4-7, 3) 8-11 and 4) 12-15). After allowing the female to acclimatize for 5 minutes within the mating vial, a male (from the same age bin) was added and the start time was recorded. The first instance of courtship was recorded and copulation start and end times were also recorded, all through visual scanning of vials. After \textasciitilde3 hours, if no copulation occurred, the female was labeled as non-receptive. Ten pairs for each treatment-population-age bin was completed, for approximately 360 total pairs analyzed.

Here I modeled the fixed effect of both treatment and age category of flies (and there interaction) with linear mixed models, with replicates of treatments as a random effect along with date. This was done for courtship latency, copulation latency, copulation duration (example below), and copulation occurrence.

The analysis of the copulation counts (using glmer() as above) displayed an error due to the 100\% success of one treatments/age to achieve copulations. This was believed to be due to a perfect separation issue, a computational error where one predictor variable perfectly predicts a response variable. The results for glmer() were similar to a much more simple glm() removing random effects in order to ensure this error is not altering my conclusions, and the results for the glmer will be displayed. Results for all models are displayed as the estimated change ($\pm$ standard error) for each treatment and age bin response, as well as the population effect, displaying Wald type II chi-square and p-value.


### Courtship Behaviours of experimentally evolved populations under Light and Dark regimes

For a more comprehensive analysis of the evolved populations (\ref{LT}) courtship behaviour, an additional experiment focusing primarily on courtship was completed (R.D). This experiment was done to determine the proportion of time each population spent courting during the day (photophase) and night (scotophase). One male (aged \textasciitilde24 hours) was placed in a vial with two immature females (less than 20 hour old that will reject copulation) (Manning 1967). Under red light, the courtship times were recorded for night time mating displays, and under normal ceiling laboratory lights, the daytime courtship times was recorded. Recording (with Logitech webcameras) in 15 minutes sessions for each replicate, the proportion of time spent courting for each male was calculated using a custom recording script for 187 mating pairs (\textasciitilde60 per treatment) over 5 days of experiments. Of interest was the proportion of time courting due to effects of treatments (evolved with mantids, spider and with no predators as controls) and the light phase (light or dark), as well as the interaction between the two, while including the observer effect.

