# Methods for Behavioural Experiments

## ***General Methods***
  
### *Predators Used*

Two generalist predators of *Drosophila melanogaster* were used throughout experimentation, zebra jumping spiders (*Salticus scenicus*) and Chinese praying mantids (*Tenodera aridifolia sinensis*). The zebra jumping spiders were collected along warm sunlight walls around Michigan State University and McMaster University campuses, and regions of Southern Ontario. The spiders were housed individually in vials at 21 C, 60% humidity and a 12:12 light:dark cycle and fed laboratory populations of flies, unless in use within population cages or prior to any experiments requiring a specific feeding regime. The Chinese praying mantids were brought into the laboratory as egg cases, either collected from fields in Southern Michigan or purchased from Nature’s Control Oregon (http://www.naturescontrol.com/). Ecolosed mantids were housed in a 32.5cm^3 mesh cages (Bugdorm-43030) and fed and maintained similarly to the spiders.


### *Populations used*

  Two different populations of *Drosophila melanogaster* were used throughout experimentation for either studying the plastic response or evolved response to predation. To measure the plastic effects of predation, a population of recently caught wild flies with little adaptation to the laboratory environment was used (Baxter et al. 2015). Using 12 populations of experimentally evolved flies undergoing different predator selection regimes allowed for the measure of the evolutionary effects on *Drosophila* due to predation (DeNieu 2014, Hangartner et al. 2017).
  
***Population of Recently Captured Flies***

This population of flies was collected in 2014 in Southern Ontario and maintained in large population cage at 25 C, 60% humidity and 12:12 light:dark cycle (lights on at 10:00 am) on a sucrose-cornmeal medium with live yeast (see General Methods: Baxter *et al.* 2015). Experimental flies were reared at similar conditions for activity experiments. For the courtship and copulation analysis, this population was housed with lights on at 8:00 am, with 12 hours of light, and reared on a molasses-cornmeal medium.
 
***Experimentally Evolved Populations with Predation Selection***

  In 2010, wild *Drosophila melanogaster* were collected at Fenn Valley vineyard in Southwest Michigan as a starting population for experimental evolution. After splitting this population into twelve 32.5 cm^3 Bugdorm mesh cages (~1500 flies per cage), each was designated a treatment. Four populations were controls with no predators present, four populations were continuously exposed to ~30 zebra jumping spiders and four populations were continuously exposed to ~30 1st instar Chinese praying mantids, with new predators cycled throughout. Each population of overlapping generations was maintained on a 12:12 light:dark cycle at 40% humidity and 24 C initially (for age-dependent mating experiments), and moved buildings/growth chambers in 2015 and housed at 60% relative humidity and 21 C (for activity analysis and light:dark mating assays) with fresh 200 mL molasses-cornmeal-yeast food bottles cycled throughout. As these populations have overlapping generations, there is no exact measure of the generations of evolution to have occurred, but is estimated to be ~ 16 generations per year. To remove any maternal effects and direct predator cues experienced by larva prior to expeimentation, populations were reared in a non-predation environment for two generations. 

### *Statistical Analysis*

Analysis was done in R version 3.3.2 (R Core Team, 2016) and fitting (generalized) linear mixed models, the *lme4* package was used (version 1.1.12, Bates *et al.* 2015). The *tidyverse* set of packages (version 1.1.0, Wickham 2017) was used for data cleaning and plotting, and the Anova function (*car* package, version 2.1.4, Fox and Weisberg 2011) was used for p-values and Wald Type II Chi-Square values.

## ***Experimental Methods: Plastic Response***

### Measures of *Drosophila* Activity with Different Olfactory Stimuli

  All activity data collection was done using two ***D**rosophila* ***A**ctivity* ***M**onitors* (DAM; Trikinetics), which counts the total times a fly crosses a laser that sits at the middle of a vial each minute over the experimental duration. These monitors were held within an undisturbed humidified chamber at 25 C with controlled hours of light (10AM) to dark (10PM). These monitors can hold small vials (22mm wide by 48 mm long) that have a snap cap lid (with ventilation hole). After the addition of ~4 ml of food (12 mm high), there is a 7mm gap between the food and the laser that will record activity.

  Many different combinations of only olfactory cues was used for these experiments, using a combination of mantids (M), field crickets (Cr), con-specific ''stimuli'' flies (F), no cue controls (C) and spiders (S) on two diets (crickets (SC) and flies (SF) (Comparisons; S:C, M:C, S:Cr and SC:SF:Cr:F). Each comparison was completed together over 24 hours in two monitors, generally ranging between 12-16 flies assayed for each treatment. All stimuli (cues) were acclimated for 3 days prior to experiment, with spiders, mantids and crickets housed singly within vials, and ''stimuli'' flies acclimated as a trio (all males). On the third day of acclimation, the ''cue'' individuals were removed along with any accompanying silks from spiders, leaving only the olfactory cues within the vials. One live sexed ''focal'' male fly from the wild caught population was aspirated into the vial. Recordings count activity over 24 hours and the data is outputted as a minute by minute count of activity for each vial.

  To account for the effects of circadian rhythm on activity, two methods were used, either imposing a circadian periodicity (sin(pi x hour/12) + cos(pi x hour/12)) or fitting a natural smooth cubic spline with 5 knots (ns(hour, 5)) for hours. As both methods showed similar results with respect to the estimated parameters of interest (results not shown), only the periodicity method is used. 

### **Observing the Influence of Predators on Mating in *Drosophila***

### Courtship Behaviours

  Using immature females (under 24 hours old) that will reject all copulation attempts, male courtship displays were recorded (Manning 1967). Using the recently caught population of flies, reared on molasses food medium, virgin male flies were collected via aspiration. These males were housed individually for two days, allowing for no social or sexual interactions. Young virgin females were collected and housed with 5 females in a vial with live yeast. Both males and females were housed at 25 C, 60% humidity and 12:12 light dark cycle prior to the experiment. 

  At the flies regular ``sunrise'' (8:00 am) a male was added (via aspiration) to a modified 4cm wide petri dish that has a layer of mesh separating the flies (on top) and a spider predator (if present) on the bottom. The spider petri dishes had the spiders acclimated 12 hours prior to the addition of the mating pair. The female was then added to the petri dish (via aspiration) and placed in an enclosed bin with a video camera recording from above. Video recordings were completed for 64 mating pairs for each treatment using Logiteck C920 HD Pro webcams, recording four chambers for 15 minutes for each assay allowed to score for the time spent courting and the number of courtship attempts.

### Copulation Behaviours

Following a similar protocol to recording courtship behaviours, copulation times were recorded for the wild caught population. Here 2 same aged virgin flies (2 days old) were used, either housed individually (males) or with 4 other flies (females). Video recordings of mating pairs was done for 30 minutes (or until the end of copulation) above four 4 cm petri dishes within an enclosed bin with either spiders in the modified petri dish or no predators. These videos were manually scored for copulation occurrence latency and duration. 70 mating pairs were recorded for each treatment, with only eighty (of 140) individual mating pairs were used for analysis of latency and duration, accounting for a little over 50% of the individual pairs found copulating.

##  ***Experimental Methods: Evolutionary Response***

### Activity Measures of Evolved Populations

  When analyzing the activity of the evolved populations, activity was measured and analysed similarly to those above for plastic response to predator cues with the exception that all populations and vials were experiencing no cues. After 2 generations reared in bottles without predators present, each population was recorded in the **DAM**. As there were many more replicates and populations of flies to measure, this was repeated in many blocks of data collection resulting in 240 individuals assayed (80 per treatment).

### Courtship and Copulation Measures in Experimentally Evolved Lineages

  Experimental flies from the F2 generation were collected as virgins every 2 days for 14 days and placed into 4 age categories (age bins by days old: 1) 1-3, 2) 4-7, 3) 8-11 and 4) 12-15). After allowing females to acclimatize for 5 minutes within the mating vial, a male (from the same age category) was added and the start time was recorded. The first instance of courtship was recorded and copulation start and end times were also recorded, all through visual scanning of vials. After ~3 hours, if no copulation occurred, the female was labeled as non-receptive. Ten pairs for each treatment-population-age bin was completed, for approximately 360 total pairs analyzed.

### Courtship Behaviours of Experimentally Evolved Populations under Light and Dark Regimes

To determine the proportion of time each population spent courting during the day (photophase) and night (scotophase), one male (aged ~24 hours) was placed in a vial with two immature females (less than 20 hour old that will reject copulation). Under red light, courtship times were recorded for night time mating displays, and under normal ceiling laboratory lights, the daytime courtship times was recorded. Recording (with Logitech web cameras) in 15 minutes sessions for each replicate, the proportion of time spent courting for each male was calculated for 187 mating pairs (~60 per treatment) over 5 days of experiments.

